### ISSUE TITLE
Support Swift4 

### ISSUE THREAD

**Issue by jeffreylyg** [inamiy/RxAutomaton#15]
Hi, when to support swift4 for this cool library?

**Comment by inamiy** [comment]
Hi, l will try Swift 4 support in the next weekend!

**Comment by jeffreylyg** [comment]
I have submitted a pull request for swift4 migration, please review the code :)

**Comment by inamiy** [comment]
Ref: #17 

Sorry for totally forgetting https://github.com/inamiy/RxAutomaton/issues/15#issuecomment-332419507 😇

**Comment by jeffreylyg** [comment]
@inamiy hi, I have adjusted the code as your advice. Please review the code again :)

**Comment by inamiy** [comment]
@jeffreylyg Thanks for contribution! I just merged #17.
