### ISSUE TITLE
 Send the library to the Cocoapods Specs repo

### ISSUE THREAD

**Issue by jeffreylyg** [inamiy/RxAutomaton#18]
Hi, can you send the library to the Cocoapods Specs repo? :)

**Comment by jeffreylyg** [comment]
Hi, could you solve this issue please?

**Comment by marcmo** [comment]
the library on cocoapods is outdated. please update the library otherwise it cannot be used as a dependency of a library project (e.g. a framework)

**Comment by inamiy** [comment]
Sorry for soooo late response 😅
I just bumped `0.4.0` (for Swift 5.0) so hope it works :)
