### ISSUE TITLE
Producer being called multiple times for one input

### ISSUE THREAD

**Issue by AndrewSB** [inamiy/RxAutomaton#3]
@inamiy I'm running into an interesting problem. I've noticed that on every state change, my observable is subscribed to twice, executing the code inside the observable twice. 

To illustrate the problem, I forked the demo, and added some logs: https://github.com/AndrewSB/RxAutomaton/blob/swift/3.0/Demo/ViewController.swift#L42

Let me know if you need anything else to repro the issue I'm having 👍 

Not sure why it's happening currently - maybe somewhere inside the source the producer is subscribed to twice?

**Comment by AndrewSB** [comment]
The problem is exasperated when the observable performs an actual side effect (mine, for example, issues a `connect` command to the bluetooth hardware on the device it's running on, and things don't turn out well when two `connect` commands are sent in succession

**Comment by inamiy** [comment]
Thanks for bug report!
This happened only in RxSwift version, and fixed in #4.
Please take a look 👀

**Comment by AndrewSB** [comment]
#4 looks great!
